/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 19
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 16
#define ALIAS_COUNT 0
#define TOKEN_COUNT 6
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_EQ_EQ_STAR_EQ_EQ = 1,
  anon_sym_EQ_EQ_PLUS_EQ_EQ = 2,
  anon_sym_EQ_EQ_DASH_EQ_EQ = 3,
  sym_line_text = 4,
  sym_line_text_nostart_eq = 5,
  sym_source_file = 6,
  sym_preamble_line = 7,
  sym_section = 8,
  sym_section_header = 9,
  sym_metadata = 10,
  sym_comment = 11,
  sym_regular_line = 12,
  aux_sym_source_file_repeat1 = 13,
  aux_sym_source_file_repeat2 = 14,
  aux_sym_section_repeat1 = 15,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ_EQ_STAR_EQ_EQ] = "==*==",
  [anon_sym_EQ_EQ_PLUS_EQ_EQ] = "==+==",
  [anon_sym_EQ_EQ_DASH_EQ_EQ] = "==-==",
  [sym_line_text] = "line_text",
  [sym_line_text_nostart_eq] = "line_text_nostart_eq",
  [sym_source_file] = "source_file",
  [sym_preamble_line] = "preamble_line",
  [sym_section] = "section",
  [sym_section_header] = "section_header",
  [sym_metadata] = "metadata",
  [sym_comment] = "comment",
  [sym_regular_line] = "regular_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_section_repeat1] = "section_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ_EQ_STAR_EQ_EQ] = anon_sym_EQ_EQ_STAR_EQ_EQ,
  [anon_sym_EQ_EQ_PLUS_EQ_EQ] = anon_sym_EQ_EQ_PLUS_EQ_EQ,
  [anon_sym_EQ_EQ_DASH_EQ_EQ] = anon_sym_EQ_EQ_DASH_EQ_EQ,
  [sym_line_text] = sym_line_text,
  [sym_line_text_nostart_eq] = sym_line_text_nostart_eq,
  [sym_source_file] = sym_source_file,
  [sym_preamble_line] = sym_preamble_line,
  [sym_section] = sym_section,
  [sym_section_header] = sym_section_header,
  [sym_metadata] = sym_metadata,
  [sym_comment] = sym_comment,
  [sym_regular_line] = sym_regular_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_section_repeat1] = aux_sym_section_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ_EQ_STAR_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ_PLUS_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ_DASH_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_line_text] = {
    .visible = true,
    .named = true,
  },
  [sym_line_text_nostart_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_preamble_line] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_regular_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_header = 1,
  field_text = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_header] = "header",
  [field_text] = "text",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_text, 0},
  [1] =
    {field_header, 0},
  [2] =
    {field_text, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') ADVANCE(20);
      if (lookahead == '=') ADVANCE(3);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '+') ADVANCE(9);
      if (lookahead == '-') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(1);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(4);
      END_STATE();
    case 9:
      if (lookahead == '=') ADVANCE(5);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(6);
      END_STATE();
    case 11:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 12:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') SKIP(13);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') SKIP(13);
      if (lookahead == '\r') SKIP(12);
      if (lookahead == '=') ADVANCE(7);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_STAR_EQ_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_PLUS_EQ_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_DASH_EQ_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_line_text);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_line_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_line_text_nostart_eq);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 13},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 13},
  [14] = {.lex_state = 13},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ_EQ_STAR_EQ_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ_PLUS_EQ_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ_DASH_EQ_EQ] = ACTIONS(1),
    [sym_line_text_nostart_eq] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(18),
    [sym_preamble_line] = STATE(2),
    [sym_section] = STATE(9),
    [sym_section_header] = STATE(4),
    [sym_metadata] = STATE(8),
    [sym_comment] = STATE(8),
    [sym_regular_line] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_source_file_repeat2] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_EQ_EQ_STAR_EQ_EQ] = ACTIONS(5),
    [anon_sym_EQ_EQ_PLUS_EQ_EQ] = ACTIONS(7),
    [anon_sym_EQ_EQ_DASH_EQ_EQ] = ACTIONS(9),
    [sym_line_text_nostart_eq] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_preamble_line] = STATE(3),
    [sym_section] = STATE(13),
    [sym_section_header] = STATE(4),
    [sym_metadata] = STATE(8),
    [sym_comment] = STATE(8),
    [sym_regular_line] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_source_file_repeat2] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_EQ_EQ_STAR_EQ_EQ] = ACTIONS(5),
    [anon_sym_EQ_EQ_PLUS_EQ_EQ] = ACTIONS(7),
    [anon_sym_EQ_EQ_DASH_EQ_EQ] = ACTIONS(9),
    [sym_line_text_nostart_eq] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym_preamble_line] = STATE(3),
    [sym_metadata] = STATE(8),
    [sym_comment] = STATE(8),
    [sym_regular_line] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_EQ_EQ_STAR_EQ_EQ] = ACTIONS(17),
    [anon_sym_EQ_EQ_PLUS_EQ_EQ] = ACTIONS(19),
    [anon_sym_EQ_EQ_DASH_EQ_EQ] = ACTIONS(22),
    [sym_line_text_nostart_eq] = ACTIONS(25),
  },
  [STATE(4)] = {
    [sym_metadata] = STATE(5),
    [sym_comment] = STATE(5),
    [sym_regular_line] = STATE(5),
    [aux_sym_section_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(28),
    [anon_sym_EQ_EQ_STAR_EQ_EQ] = ACTIONS(30),
    [anon_sym_EQ_EQ_PLUS_EQ_EQ] = ACTIONS(7),
    [anon_sym_EQ_EQ_DASH_EQ_EQ] = ACTIONS(9),
    [sym_line_text_nostart_eq] = ACTIONS(11),
  },
  [STATE(5)] = {
    [sym_metadata] = STATE(6),
    [sym_comment] = STATE(6),
    [sym_regular_line] = STATE(6),
    [aux_sym_section_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(32),
    [anon_sym_EQ_EQ_STAR_EQ_EQ] = ACTIONS(34),
    [anon_sym_EQ_EQ_PLUS_EQ_EQ] = ACTIONS(7),
    [anon_sym_EQ_EQ_DASH_EQ_EQ] = ACTIONS(9),
    [sym_line_text_nostart_eq] = ACTIONS(11),
  },
  [STATE(6)] = {
    [sym_metadata] = STATE(6),
    [sym_comment] = STATE(6),
    [sym_regular_line] = STATE(6),
    [aux_sym_section_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(36),
    [anon_sym_EQ_EQ_STAR_EQ_EQ] = ACTIONS(38),
    [anon_sym_EQ_EQ_PLUS_EQ_EQ] = ACTIONS(40),
    [anon_sym_EQ_EQ_DASH_EQ_EQ] = ACTIONS(43),
    [sym_line_text_nostart_eq] = ACTIONS(46),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(49), 2,
      ts_builtin_sym_end,
      sym_line_text_nostart_eq,
    ACTIONS(51), 3,
      anon_sym_EQ_EQ_STAR_EQ_EQ,
      anon_sym_EQ_EQ_PLUS_EQ_EQ,
      anon_sym_EQ_EQ_DASH_EQ_EQ,
  [10] = 2,
    ACTIONS(53), 2,
      ts_builtin_sym_end,
      sym_line_text_nostart_eq,
    ACTIONS(55), 3,
      anon_sym_EQ_EQ_STAR_EQ_EQ,
      anon_sym_EQ_EQ_PLUS_EQ_EQ,
      anon_sym_EQ_EQ_DASH_EQ_EQ,
  [20] = 4,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 1,
      anon_sym_EQ_EQ_STAR_EQ_EQ,
    STATE(4), 1,
      sym_section_header,
    STATE(14), 2,
      sym_section,
      aux_sym_source_file_repeat2,
  [34] = 2,
    ACTIONS(59), 2,
      ts_builtin_sym_end,
      sym_line_text_nostart_eq,
    ACTIONS(61), 3,
      anon_sym_EQ_EQ_STAR_EQ_EQ,
      anon_sym_EQ_EQ_PLUS_EQ_EQ,
      anon_sym_EQ_EQ_DASH_EQ_EQ,
  [44] = 2,
    ACTIONS(63), 2,
      ts_builtin_sym_end,
      sym_line_text_nostart_eq,
    ACTIONS(65), 3,
      anon_sym_EQ_EQ_STAR_EQ_EQ,
      anon_sym_EQ_EQ_PLUS_EQ_EQ,
      anon_sym_EQ_EQ_DASH_EQ_EQ,
  [54] = 2,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      sym_line_text_nostart_eq,
    ACTIONS(69), 3,
      anon_sym_EQ_EQ_STAR_EQ_EQ,
      anon_sym_EQ_EQ_PLUS_EQ_EQ,
      anon_sym_EQ_EQ_DASH_EQ_EQ,
  [64] = 4,
    ACTIONS(57), 1,
      anon_sym_EQ_EQ_STAR_EQ_EQ,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_section_header,
    STATE(14), 2,
      sym_section,
      aux_sym_source_file_repeat2,
  [78] = 4,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 1,
      anon_sym_EQ_EQ_STAR_EQ_EQ,
    STATE(4), 1,
      sym_section_header,
    STATE(14), 2,
      sym_section,
      aux_sym_source_file_repeat2,
  [92] = 1,
    ACTIONS(78), 1,
      sym_line_text,
  [96] = 1,
    ACTIONS(80), 1,
      sym_line_text,
  [100] = 1,
    ACTIONS(82), 1,
      sym_line_text,
  [104] = 1,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 10,
  [SMALL_STATE(9)] = 20,
  [SMALL_STATE(10)] = 34,
  [SMALL_STATE(11)] = 44,
  [SMALL_STATE(12)] = 54,
  [SMALL_STATE(13)] = 64,
  [SMALL_STATE(14)] = 78,
  [SMALL_STATE(15)] = 92,
  [SMALL_STATE(16)] = 96,
  [SMALL_STATE(17)] = 100,
  [SMALL_STATE(18)] = 104,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 1, 0, 2),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 1, 0, 2),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 2),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 2, 0, 2),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular_line, 1, 0, 1),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regular_line, 1, 0, 1),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preamble_line, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preamble_line, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 2, 0, 3),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 2, 0, 3),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 2, 0, 3),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata, 2, 0, 3),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 3),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 3),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(15),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [84] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hotcrp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hotcrp",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
